### ISSUE TITLE
[FEAT] 24.08 branch

### ISSUE THREAD

**Issue by BrycensRanch** [flathub/org.freedesktop.Sdk.Extension.golang#109]
I want to use 24.08 in my upcoming application but this is a blocker for me since there’s no 24.08 branch yet for this SDK. I can PR it now

**Comment by klugier** [comment]
Plus one one my side as well. I can not upgrade to 24.08 for https://github.com/flathub/org.ultimatepp.TheIDE. PR is not an option since you need to create new separate branch... The repository maintainers need to do it.

**Comment by klugier** [comment]
Just a question when we can expect new 24.08 branch?

**Comment by bbhtt** [comment]
> PR is not an option since you need to create new separate branch..

You can make a PR, I can merge it to a separate branch. Nothing prevents making PRs, they are welcome.

> Just a question when we can expect new 24.08 branch?

when it's created.

**Comment by klugier** [comment]
@bbhtt PR is ready #111 is ready. All checks passed with SDK 24.04. Please merge and create new branch. Thanks in advanced!

Sincer there are some commits, please use squash and merge strategy.

**Comment by klugier** [comment]
Thanks @bbhtt!
