### ISSUE TITLE
Update/Upgrade to Freedesktop 18.08

### ISSUE THREAD

**Issue by amtlib-dot-dll** [flathub/org.freedesktop.Sdk.Extension.golang#4]
flathub/org.freedesktop.Sdk.Extension.gcc8#3
flathub/org.freedesktop.Sdk.Extension.openjdk10#5

Thanks!

**Comment by barthalion** [comment]
Effectively I don't think it matters as it repackages tarballs with binaries from upstream so nothing is technically tied to specific runtime version.

**Comment by jurf** [comment]
But is there a way that I can use it with fd.o 18.08 then?

**Comment by barthalion** [comment]
Fixed for a while already.
