### ISSUE TITLE
Package Delve with Golang

### ISSUE THREAD

**Issue by amtlib-dot-dll** [flathub/org.freedesktop.Sdk.Extension.golang#5]
As stated in https://golang.org/doc/gdb

> Note that [Delve](https://github.com/derekparker/delve) is a better alternative to GDB when debugging Go programs built with the standard toolchain. It understands the Go runtime, data structures, and expressions better than GDB. Delve currently supports Linux, OSX, and Windows on amd64. For the most up-to-date list of supported platforms, please see [the Delve documentation](https://github.com/derekparker/delve/tree/master/Documentation/installation).

The building process is [here](https://github.com/derekparker/delve/blob/master/Documentation/installation/linux/install.md).

Thank you very much!

-----

BTW, [Visual Studio Code](https://github.com/microsoft/vscode-go#optional-debugging) requires Delve to do the debugging job

**Comment by TingPing** [comment]
Same discussion as #3
