### ISSUE TITLE
Branch 23.08 not updated

### ISSUE THREAD

**Issue by maciejaszek** [flathub/org.freedesktop.Sdk.Extension.golang#96]
Branch 23.08 received no updates since its creation. As a result on branch 23.08 Go has version 1.21.0, while latest version is 1.21.4 (this version is also available also on branch 22.08).

**Comment by maciejaszek** [comment]
@hfiguiere Probably it's caused by 22.08 being the default branch (it's still being updated). Could you fix that?

**Comment by hfiguiere** [comment]
changed the default branch

**Comment by maciejaszek** [comment]
Updates are working. Thanks!
